export const THEME = {
  colors: {
    primary: '#2c3e50',
    secondary: '#3498db',
    success: '#2ecc71',
    danger: '#e74c3c',
    warning: '#f39c12',
    info: '#1abc9c',
    light: '#ecf0f1',
    dark: '#2c3e50',
    white: '#ffffff',
    black: '#000000',
    gray: '#95a5a6',
    lightGray: '#bdc3c7',
    darkGray: '#7f8c8d',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: 'bold' },
    h2: { fontSize: 28, fontWeight: 'bold' },
    h3: { fontSize: 24, fontWeight: 'bold' },
    h4: { fontSize: 20, fontWeight: 'bold' },
    h5: { fontSize: 18, fontWeight: 'bold' },
    body: { fontSize: 16 },
    caption: { fontSize: 14 },
    small: { fontSize: 12 },
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    round: 999,
  },
};
